[tool.poetry]
name = "gqiwiapi"
version = "0.1.0"
description = ""
authors = ["Gnifajio <gnifajio@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytz = "^2022.7"
httpx = "^0.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
